packages:
  - packages/*
  - docs
  - packages/*/playground
catalog:
  '@antfu/eslint-config': ^3.6.0
  '@iconify-json/ri': ^1.2.0
  '@iconify-json/svg-spinners': ^1.2.0
  '@shikijs/markdown-it': ^1.17.0
  '@shikijs/transformers': ^1.17.0
  '@shikijs/twoslash': ^1.17.0
  '@shikijs/vitepress-twoslash': ^1.17.0
  '@types/eslint': ^9.6.1
  '@types/node': ^22.5.4
  '@types/react': ^18.3.5
  '@types/react-dom': ^18.3.0
  '@typescript/ata': ^0.9.7
  '@typescript/twoslash': ^3.2.8
  '@typescript/vfs': ^1.6.0
  '@unocss/reset': ^0.62.3
  '@vitest/coverage-v8': ^2.1.0
  '@vue/language-core': ~2.1.6
  '@vueuse/core': ^11.0.3
  bumpp: ^9.5.2
  eslint: ^9.10.0
  esno: ^4.7.0
  fast-glob: ^3.3.2
  floating-vue: ^5.2.2
  fuse.js: ^7.0.0
  idb-keyval: ^6.2.1
  jiti: ^1.21.6
  lint-staged: ^15.2.10
  lz-string: ^1.5.0
  mlly: ^1.7.1
  ohash: ^1.1.3
  preact: ^10.23.2
  pretty-format: ^29.7.0
  react: ^18.3.1
  sass: ^1.78.0
  shiki: ^1.17.0
  simple-git-hooks: ^2.11.1
  tslib: ^2.7.0
  typescript: ^5.6.2
  unbuild: ^2.0.0
  unocss: ^0.62.3
  unplugin-vue-components: ^0.27.4
  unstorage: ^1.12.0
  vite: ^5.4.4
  vite-tsconfig-paths: ^5.0.1
  vitepress: ^1.3.4
  vitest: ^2.1.0
  vue: 3.5.3
